# Spring Boot Web ?????
server:
  port: 8081

# Spring ??
spring:
  # ?????
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis ??
  data:
    redis:
      # Redis ?????
      host: 127.0.0.1
      # Redis ?????
      port: 6379
      # Redis ????? (???0)
      database: 0
      # Redis ??????? (??????????????)
      # password: your_redis_password
      # ??????
      timeout: 10000ms
      lettuce:
        pool:
          # ???????? (????????)
          max-active: 8
          # ??????????? (????????)
          max-wait: -1ms
          # ???????????
          max-idle: 8
          # ???????????
          min-idle: 0
mybatis-plus:
  enableLogicDelete: true
  mapperPackage: xlike.top.**.mapper
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: xlike.top.nettydemo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




# Sa-Token ??
sa-token:
  # token ?? (Cookie?Header?Query?????)
  token-name: "nettyTest"
  # token ??????s (??30?)
  timeout: 2592000
  # token ?????????s (??????????token?????????-1??????)
  active-timeout: 1800
  # ???????????? (?true?????????????)
  is-concurrent: true
  # ?????????????????token (?true???????????token??????????????????????)
  is-share: false
  # token ??
  token-style: "uuid"
  # ????????
  is-log: true
  dao: sa-token-dao-redis-jackson


# Netty ???????
netty:
  # Netty ?????
  port: 8090
  # Boss ????????????? 1
  boss-threads: 1
  # Worker ????????0 ??? Netty ?? CPU ????????CPU * 2?
  worker-threads: 0
  # WebSocket ?????
  websocket-path: "/ws"
  # ??????????????????????????????
  reader-idle-seconds: 45
  # ???????????????????????????????
  writer-idle-seconds: 20
  # WebSocket ???????????? (1MB)
  max-ws-frame-size: 1048576
  # ????????????
  backlog: 1024
  # ???? TCP Nagle ???true ???????????
  tcp-no-delay: true
  # ???? TCP ??? SO_KEEPALIVE ??
  so-keep-alive: true
  # ???????????????Channel??????
  write-buffer-watermark-low: 32768 # 32KB
  # ???????????????Channel???????
  write-buffer-watermark-high: 65536 # 64KB